var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var controller = require('../controllers/users.js');
router.use(bodyParser.json());
router.get('/:userId?', controller.getUsers);
router.get('/:userId/signature', controller.getUserSignature);
router.post('/screenname/suggest', controller.suggestScreenname);
router.post('/screenname/:screenname', controller.checkScreenName);
router.post('/validate', controller.validateUser);
router.post('/', controller.postUser);
router.delete('/:userId', controller.deleteUser);
router.post('/:userId/activate', controller.activateUser);
router.post('/:userId/deactivate',controller.deactivateUser);
module.exports = router;
